-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spqr]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [core::num::error::TryFromIntError]
    Source: '/rustc/library/core/src/num/error.rs', lines 10:0-10:26
    Name pattern: [core::num::error::TryFromIntError] -/
@[rust_type "core::num::error::TryFromIntError"]
axiom core.num.error.TryFromIntError : Type

/-- [alloc::collections::vec_deque::into_iter::IntoIter]
    Source: '/rustc/library/alloc/src/collections/vec_deque/into_iter.rs', lines 18:0-21:1
    Name pattern: [alloc::collections::vec_deque::into_iter::IntoIter] -/
@[rust_type "alloc::collections::vec_deque::into_iter::IntoIter"]
axiom alloc.collections.vec_deque.into_iter.IntoIter (T : Type) (A : Type) :
  Type

/-- [alloc::collections::vec_deque::VecDeque]
    Source: '/rustc/library/alloc/src/collections/vec_deque/mod.rs', lines 104:0-107:1
    Name pattern: [alloc::collections::vec_deque::VecDeque] -/
@[rust_type "alloc::collections::vec_deque::VecDeque"]
axiom alloc.collections.vec_deque.VecDeque (T : Type) (A : Type) : Type

/-- [bytes::buf::uninit_slice::UninitSlice]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.10.1/src/buf/uninit_slice.rs', lines 22:0-22:22
    Name pattern: [bytes::buf::uninit_slice::UninitSlice] -/
@[rust_type "bytes::buf::uninit_slice::UninitSlice"]
axiom bytes.buf.uninit_slice.UninitSlice : Type

/-- [libcrux_ml_kem::mlkem768::incremental::KeyPairCompressedBytes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-ml-kem-0.0.7/src/mlkem.rs', lines 233:8-233:41
    Name pattern: [libcrux_ml_kem::mlkem768::incremental::KeyPairCompressedBytes] -/
@[rust_type "libcrux_ml_kem::mlkem768::incremental::KeyPairCompressedBytes"]
axiom libcrux_ml_kem.mlkem768.incremental.KeyPairCompressedBytes : Type

/-- [prost::encoding::DecodeContext]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/prost-0.14.1/src/encoding.rs', lines 36:0-36:24
    Name pattern: [prost::encoding::DecodeContext] -/
@[rust_type "prost::encoding::DecodeContext"]
axiom prost.encoding.DecodeContext : Type

/-- [prost::error::DecodeError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/prost-0.14.1/src/error.rs', lines 17:0-17:22
    Name pattern: [prost::error::DecodeError] -/
@[rust_type "prost::error::DecodeError"]
axiom prost.error.DecodeError : Type

/-- [sorted_vec::SortedVec]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 27:0-27:30
    Name pattern: [sorted_vec::SortedVec] -/
@[rust_type "sorted_vec::SortedVec"]
axiom sorted_vec.SortedVec {T : Type} (corecmpOrdInst : core.cmp.Ord T) : Type

/-- [sorted_vec::SortedSet]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 39:0-39:30
    Name pattern: [sorted_vec::SortedSet] -/
@[rust_type "sorted_vec::SortedSet"]
axiom sorted_vec.SortedSet {T : Type} (corecmpOrdInst : core.cmp.Ord T) : Type

