/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE-APACHE.
Authors: Hoang Le Truong
-/
import SrcTranslated.Funs
import SrcTranslated.FunsExternal
/-!
# Spec theorem for `core::iter::range::{core::iter::range::Step for i32}::backward_checked`

In Rust's standard library, `Step::backward_checked` for `i32` computes the checked backward step
of a range iterator.  Given `start : i32` and `count : usize`, it attempts to compute
`start − count` and returns `Some(result)` if the result fits in `i32`, `None` otherwise.

The Rust implementation (from `/rustc/library/core/src/iter/range.rs`, lines 340:16-340:74) is
generated by the `step_signed_integer!` macro applied to `i32`:
  ```rust
  // Inside: unsafe impl Step for i32 { ... }
  // Source: /rustc/library/core/src/iter/range.rs, lines 340:16-340:74
  fn backward_checked(start: i32, count: usize) -> Option<i32> {
      match i32::try_from(count) {
          Ok(count) => start.checked_sub(count),
          Err(_) => None,    // count > i32::MAX
      }
  }
  ```

The function proceeds in two stages:
  1. Convert `count : usize` to `i32` via `i32::try_from(count)`.
     If `count > i32::MAX` (= 2³¹ − 1), the conversion fails and `None` is returned immediately.
  2. If the conversion succeeds, compute `start.checked_sub(count)`, which returns
     `Some(start - count)` when the subtraction does not overflow `i32`, and `None` otherwise.

The combined condition for returning `Some(z)` with `z = start − count` is that the mathematical
integer difference `start − count` lies within the representable range of `i32`:
  `i32::MIN ≤ start − count ≤ i32::MAX`   i.e.   `−2³¹ ≤ start − count ≤ 2³¹ − 1`

This is the backward (subtraction) counterpart of `Step::forward_checked`, which computes
`start + count` with the same overflow-checking semantics.  Together they allow `Range<i32>` to
advance and retreat its iterator bounds with compile-time-verified arithmetic safety.

**Source**: /rustc/library/core/src/iter/range.rs (lines 340:16-340:74)
-/

open Aeneas Aeneas.Std Result

namespace spqr.I32.Insts.CoreIterRangeStep

/--
**Behavioral axiom for `I32.Insts.CoreIterRangeStep.backward_checked`**:

Concrete model of Rust's `Step::backward_checked` for `i32`:
given `start : I32` and `count : Usize`, compute the integer difference
`start.val − count.val` and return `Some(result)` if it fits in `I32`,
`None` otherwise.  The outer `Result` is always `ok` (the call never panics).

The Aeneas-extracted Lean declaration (SrcTranslated/FunsExternal.lean, lines 328–334):
  ```lean
  @[rust_fun
    "core::iter::range::{core::iter::range::Step<i32>}::backward_checked"]
  axiom I32.Insts.CoreIterRangeStep.backward_checked
    : Std.I32 → Std.Usize → Result (Option Std.I32)
  ```

This axiom pins down the behavior to match the Rust semantics:
  `backward_checked start count = ok (IScalar.tryMkOpt .I32 (start.val − count.val))`

The `IScalar.tryMkOpt .I32 z` helper returns `some ⟨z, _⟩` when `I32.min ≤ z ≤ I32.max`,
and `none` otherwise, faithfully modelling `i32::checked_sub`.

Compare with the concrete definition of `forward_checked` (FunsExternal.lean, lines 336–349):
  ```lean
  def I32.Insts.CoreIterRangeStep.forward_checked
    : Std.I32 → Std.Usize → Result (Option Std.I32) :=
    fun start n => ok (IScalar.tryMkOpt .I32 (start.val + n.val))
  ```

The Rust code that this axiom models:
  ```rust
  fn backward_checked(start: i32, count: usize) -> Option<i32> {
      match i32::try_from(count) {
          Ok(count) => start.checked_sub(count),
          Err(_) => None,
      }
  }
  ```

**Source**: /rustc/library/core/src/iter/range.rs (lines 340:16-340:74)
-/
axiom backward_checked_eq (start : I32) (count : Usize) :
    backward_checked start count = ok (IScalar.tryMkOpt .I32 (start.val - count.val))

/--
**Spec theorem for `Step<i32>::backward_checked` (general `n`)**:

• Takes an `I32` value `start` and an arbitrary step count `n : Usize`.
• Computes the checked subtraction `start − n`.
• Returns:
    - `some z` with `z.val = start.val − n.val` when
      `I32.min ≤ start.val − n.val ∧ start.val − n.val ≤ I32.max`
      i.e. the mathematical difference fits in `[−2³¹, 2³¹ − 1]`;
    - `none` when the difference falls outside the representable range of `i32`.

The Rust source (`Step::backward_checked` for `i32`) for general `count`:
  ```rust
  fn backward_checked(start: i32, count: usize) -> Option<i32> {
      // Step 1: try to convert count : usize → i32
      //   Succeeds when count ≤ i32::MAX (= 2_147_483_647)
      //   Fails (returns None) when count > i32::MAX
      // Step 2: if conversion succeeded, compute start.checked_sub(count)
      //   Returns Some(start - count) if i32::MIN ≤ start - count ≤ i32::MAX
      //   Returns None on underflow (start - count < i32::MIN)
      match i32::try_from(count) {
          Ok(count) => start.checked_sub(count),
          Err(_) => None,
      }
  }
  ```

The result satisfies the value-level specification:

  `match result with`
  `| some z => I32.min ≤ start.val − n.val ∧ start.val − n.val ≤ I32.max`
  `           ∧ z.val = start.val − n.val`
  `| none   => ¬ (I32.min ≤ start.val − n.val ∧ start.val − n.val ≤ I32.max)`

The proof rewrites `backward_checked` using the behavioral axiom `backward_checked_eq`,
reduces to `IScalar.tryMkOpt`, and case-splits on whether `start.val − n.val` fits in `I32`.

Compare with the analogous `forward_checked` definition (FunsExternal.lean, lines 347–349):
  ```lean
  def I32.Insts.CoreIterRangeStep.forward_checked
    : Std.I32 → Std.Usize → Result (Option Std.I32) :=
    fun start n => ok (IScalar.tryMkOpt .I32 (start.val + n.val))
  ```

**Source**: /rustc/library/core/src/iter/range.rs (lines 340:16-340:74)
-/
@[step]
theorem backward_checked_spec
    (start : I32) (n : Usize) :
     backward_checked start n ⦃ (opt : Option I32) =>
      match opt with
      | some z => I32.min ≤ start.val - n.val ∧ start.val - n.val ≤ I32.max
                  ∧ z.val = start.val - n.val
      | none   => ¬ (I32.min ≤ start.val - n.val ∧ start.val - n.val ≤ I32.max) ⦄ := by
  suffices h : ∃ opt,
      backward_checked start n = ok opt ∧
      (I32.min ≤ start.val - n.val ∧ start.val - n.val ≤ I32.max →
          ∃ z, opt = some z ∧ z.val = start.val - n.val) ∧
      (¬ (I32.min ≤ start.val - n.val ∧ start.val - n.val ≤ I32.max) →
          opt = none) by grind
  rw [backward_checked_eq]
  have htry := IScalar.tryMkOpt_eq .I32 (start.val - n.val)
  generalize IScalar.tryMkOpt .I32 (start.val - n.val) = opt at htry ⊢
  cases opt with
  | none => grind
  | some z =>
    refine ⟨some z, rfl, fun _ => ⟨z, rfl, by grind⟩, fun h => by grind⟩

end spqr.I32.Insts.CoreIterRangeStep
