/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE-APACHE.
Authors: Hoang Le Truong
-/
import SrcTranslated.Funs
import SrcTranslated.FunsExternal
/-!
# Spec theorem for `core::iter::range::{core::iter::range::Step for i32}::steps_between`

In Rust's standard library, `Step::steps_between` for `i32` computes the number of successor steps
needed to get from `start` to `end`.  Given `start : &i32` and `end : &i32`, it returns a pair
`(usize, Option<usize>)` where:

- If `start > end`: the range is empty, so `(0, Some(0))`.
- If `start ≤ end`: the number of steps is `end − start` (widened to `i64` to avoid overflow).
  If that difference fits in `usize`, both components equal the difference.
  If it doesn't fit (only possible on platforms with `usize` < 64 bits), the first component is
  `usize::MAX` (a saturated lower bound) and the second is `None`.

The Rust implementation (from `/rustc/library/core/src/iter/range.rs`, lines 304:16-304:84) is
generated by the `step_signed_integer!` macro applied to `i32`:
  ```rust
  // Inside: unsafe impl Step for i32 { ... }
  // Source: /rustc/library/core/src/iter/range.rs, lines 304:16-304:84
  fn steps_between(start: &i32, end: &i32) -> (usize, Option<usize>) {
      if *start <= *end {
          // Widen both to i64 to avoid overflow; for i32 the difference always fits in i64.
          match usize::try_from((*end as i64) - (*start as i64)) {
              Ok(steps) => (steps, Some(steps)),
              Err(_) => (usize::MAX, None),    // diff > usize::MAX
          }
      } else {
          (0, Some(0))
      }
  }
  ```

The function proceeds as follows:
  1. Compare `start` and `end`.
  2. If `start > end`, the range `start..end` is empty, so return `(0, Some(0))`.
  3. If `start ≤ end`, widen both to `i64` and compute `diff = end − start` (always ≥ 0).
  4. Try to convert `diff` to `usize` via `usize::try_from(diff)`:
     - If it fits: return `(diff as usize, Some(diff as usize))`.
     - If it overflows `usize`: return `(usize::MAX, None)`.

For `i32`, the maximum possible difference is `i32::MAX − i32::MIN = 2³² − 1 = 4294967295`,
which always fits in `usize` on 64-bit platforms.  However, on a hypothetical 32-bit platform
(where `usize::MAX = 2³¹ − 1`), differences exceeding `usize::MAX` would return `None`.

This is the step-counting function used by `Range<i32>` to implement `Iterator::size_hint`,
`ExactSizeIterator::len`, and related iterator traits that need to know how many elements
remain in the range.

Compare with the companion functions in the same `Step for i32` implementation:
  - `forward_checked(start, count)`:  computes `start + count` with overflow check.
  - `backward_checked(start, count)`: computes `start − count` with overflow check.

**Source**: /rustc/library/core/src/iter/range.rs (lines 304:16-304:84)
-/

open Aeneas Aeneas.Std Result

namespace spqr.I32.Insts.CoreIterRangeStep

-- Bring the Aeneas-extracted axiom into scope
private noncomputable abbrev sb := I32.Insts.CoreIterRangeStep.steps_between

/--
Concrete model of the `steps_between` return value, using `UScalar.tryMkOpt`:

  - If `start.val ≤ end_.val`:
    let `o := UScalar.tryMkOpt .Usize (end_.val − start.val).toNat`.
    - If `o = some n` (diff fits in `Usize`): return `(n, some n)`.
      This models Rust's `Ok(steps) => (steps, Some(steps))`.
    - If `o = none` (diff overflows `Usize`): return `(core.num.Usize.MAX, none)`.
      This models Rust's `Err(_) => (usize::MAX, None)`.
  - If `start.val > end_.val`: return `(0, some 0)`.
    This models Rust's `(0, Some(0))`.

Rust source:
  ```rust
  fn steps_between(start: &i32, end: &i32) -> (usize, Option<usize>) {
      if *start <= *end {
          match usize::try_from((*end as i64) - (*start as i64)) {
              Ok(steps) => (steps, Some(steps)),
              Err(_) => (usize::MAX, None),
          }
      } else {
          (0, Some(0))
      }
  }
  ```
-/
def steps_between_val (start end_ : I32) : Usize × Option Usize :=
  if start.val ≤ end_.val then
    match UScalar.tryMkOpt .Usize (end_.val - start.val).toNat with
    | some n => (n, some n)                -- Ok(steps) => (steps, Some(steps))
    | none   => (core.num.Usize.MAX, none) -- Err(_)    => (usize::MAX, None)
  else
    (0#usize, some 0#usize)                -- (0, Some(0))

/--
**Behavioral axiom for `I32.Insts.CoreIterRangeStep.steps_between`**:

Concrete model of Rust's `Step::steps_between` for `i32`:
given `start : I32` and `end_ : I32`, compute the number of successor steps from `start` to
`end_` and return a pair `(lo, hi)` where `lo : Usize` and `hi : Option Usize`.

The Aeneas-extracted Lean declaration (SrcTranslated/FunsExternal.lean):
  ```lean
  /-- [core::iter::range::{core::iter::range::Step for i32}::steps_between]:
      Source: '/rustc/library/core/src/iter/range.rs', lines 304:16-304:84
      Name pattern: [core::iter::range::{core::iter::range::Step<i32>}::steps_between] -/
  @[rust_fun "core::iter::range::{core::iter::range::Step<i32>}::steps_between"]
  axiom I32.Insts.CoreIterRangeStep.steps_between
    : Std.I32 → Std.I32 → Result (Std.Usize × (Option Std.Usize))
  ```

This axiom pins down the behavior to match the Rust semantics:

  `sb start end_ = ok (steps_between_val start end_)`

where `steps_between_val` uses `UScalar.tryMkOpt .Usize` to model Rust's
`usize::try_from(...)`, faithfully reproducing the three branches:
  - **`start.val > end_.val`**: `(0#usize, some 0#usize)` — empty range.
  - **`start.val ≤ end_.val` and diff fits**: `(n, some n)` — exact count.
  - **`start.val ≤ end_.val` and diff overflows**: `(core.num.Usize.MAX, none)` — saturated.

The outer `Result` is always `ok` — the call never panics.

The Rust code that this axiom models:
  ```rust
  fn steps_between(start: &i32, end: &i32) -> (usize, Option<usize>) {
      if *start <= *end {
          match usize::try_from((*end as i64) - (*start as i64)) {
              Ok(steps) => (steps, Some(steps)),
              Err(_) => (usize::MAX, None),
          }
      } else {
          (0, Some(0))
      }
  }
  ```

Compare with the analogous `backward_checked` axiom (Spqr/Specs/Test/Clone.lean):
  ```lean
  axiom backward_checked_eq (start : I32) (count : Usize) :
      backward_checked start count = ok (IScalar.tryMkOpt .I32 (start.val - count.val))
  ```

**Source**: /rustc/library/core/src/iter/range.rs (lines 304:16-304:84)
-/
theorem steps_between_eq (start end_ : I32) :
    sb start end_ = ok (steps_between_val start end_) := by
  simp only [sb, I32.Insts.CoreIterRangeStep.steps_between, steps_between_val]

/--
**Spec theorem for `Step<i32>::steps_between` (general `start`, `end_`)**:

• Takes two `I32` values `start` and `end_`.
• Computes the number of steps between them.
• Returns a pair `(lo, hi)`:
    - When `start.val > end_.val` (empty range):
      `lo.val = 0` and `hi = some lo` (both components represent 0 steps).
    - When `start.val ≤ end_.val`:
      let `diff = (end_.val − start.val).toNat`;
      - If `diff ≤ Usize.max`:
        `lo.val = diff`, `hi = some n`, `n.val = diff` (exact step count in both components).
      - If `diff > Usize.max` (overflow):
        `lo.val = Usize.max`, `hi = none` (saturated lower bound, inexact).

The Rust source (`Step::steps_between` for `i32`):
  ```rust
  fn steps_between(start: &i32, end: &i32) -> (usize, Option<usize>) {
      if *start <= *end {
          // Widen to i64 to avoid overflow
          match usize::try_from((*end as i64) - (*start as i64)) {
              Ok(steps) => (steps, Some(steps)),
              Err(_) => (usize::MAX, None),
          }
      } else {
          (0, Some(0))
      }
  }
  ```

The result satisfies the value-level specification:

  `if start.val ≤ end_.val then`
  `  let diff := (end_.val − start.val).toNat`
  `  match pair.2 with`
  `  | some hi => diff ≤ Usize.max ∧ pair.1.val = diff ∧ hi.val = diff`
  `  | none    => ¬ (diff ≤ Usize.max) ∧ pair.1.val = Usize.max`
  `else`
  `  pair.1.val = 0 ∧ pair.2 = some pair.1`

The proof rewrites via the behavioral axiom `steps_between_eq`, unfolds
`steps_between_val`, and uses `UScalar.tryMkOpt_eq` to case-split on whether the difference
fits in `Usize`.

**Source**: /rustc/library/core/src/iter/range.rs (lines 304:16-304:84)
-/
@[step]
theorem steps_between_spec
    (start end_ : I32) :
    sb start end_ ⦃ (pair : Usize × Option Usize) =>
      if start.val ≤ end_.val then
        let diff := (end_.val - start.val).toNat
        match pair.2 with
        | some hi => diff ≤ Usize.max ∧ pair.1.val = diff ∧ hi.val = diff
        | none    => ¬ (diff ≤ Usize.max) ∧ pair.1.val = Usize.max
      else
        pair.1.val = 0 ∧ pair.2 = some pair.1 ⦄ := by
  rw [steps_between_eq]
  simp only [WP.spec_ok, steps_between_val]
  have htry := UScalar.tryMkOpt_eq .Usize (end_.val - start.val).toNat
  by_cases hle : start.val ≤ end_.val
  · -- Case: start ≤ end (non-empty range)
    rw [if_pos hle]
    generalize UScalar.tryMkOpt .Usize (end_.val - start.val).toNat = o at htry ⊢
    cases o with
    | some n =>
      -- Sub-case: diff fits in Usize — tryMkOpt returned some n
      simp only [if_pos hle]
      obtain ⟨hval, hbounds⟩ := htry
      exact ⟨by scalar_tac, hval, hval⟩
    | none =>
      -- Sub-case: diff overflows Usize — tryMkOpt returned none
      simp only [core.num.Usize.MAX, Usize.ofNatCore_val_eq, if_pos hle]
      exact ⟨by scalar_tac, rfl⟩
  · -- Case: start > end (empty range)
    rw [if_neg hle, if_neg hle]
    simp only [UScalar.ofNatCore_val_eq]
    constructor <;> trivial

end spqr.I32.Insts.CoreIterRangeStep
